# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Learn\大学课程\数字图像处理\课程设计\Source\GUI\UI\design\main0928.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1315, 940)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame#frame{\n"
"    background-color: qlineargradient(x0:0, y0:1, x1:1, y1:1,stop:0.4  rgb(107, 128, 210), stop:1 rgb(180, 140, 255));\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("QFrame{\n"
"    background-color: rgba(255, 255, 255,0);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.widget_2 = QtWidgets.QWidget(self.frame_4)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 12, 0, 8)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setMinimumSize(QtCore.QSize(64, 64))
        self.widget.setMaximumSize(QtCore.QSize(64, 64))
        self.widget.setStyleSheet("image: url(:/svg/img/img/java.jpg);\n"
"")
        self.widget.setObjectName("widget")
        self.horizontalLayout_3.addWidget(self.widget)
        self.verticalLayout.addWidget(self.widget_2)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_6.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.verticalLayout.addWidget(self.frame_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.listWidget = QtWidgets.QListWidget(self.frame_3)
        self.listWidget.setStyleSheet("QListView {\n"
"\n"
"}\n"
"QListView::item{\n"
"background-color: transparent;\n"
"    color: rgba(255, 255, 255, 199);\n"
"padding:12px;\n"
"padding-left:18px;\n"
"}\n"
"QListView::item:hover {\n"
"    background-color: rgba(175, 139, 255, 59);\n"
"\n"
"}\n"
"QListView::item:selected {\n"
"background-color: rgba(175, 139, 255, 159);\n"
"    color: rgb(255, 255, 255);\n"
"border-left:5px solid rgb(172, 154, 233)\n"
"}\n"
"")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        item.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/首页_home-two.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/文字讯息_text-message.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        item.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/日历_calendar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        item.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/buttom_white/img/buttom_white/设置_setting-two.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.listWidget.addItem(item)
        self.verticalLayout_2.addWidget(self.listWidget)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(245, 249, 254);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_30.setContentsMargins(48, 24, 48, 24)
        self.verticalLayout_30.setSpacing(4)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_33.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        spacerItem2 = QtWidgets.QSpacerItem(761, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem2)
        self.label_54 = QtWidgets.QLabel(self.frame_9)
        self.label_54.setStyleSheet("color: rgb(198, 198, 198);")
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_33.addWidget(self.label_54)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_5.setMinimumSize(QtCore.QSize(41, 41))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"border: none;\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"}\n"
"")
        self.pushButton_5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/buttom/img/buttom/耳机声音_headphone-sound.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_33.addWidget(self.pushButton_5)
        self.verticalLayout_30.addWidget(self.frame_9)
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_30.addWidget(self.label)
        self.page_window = QtWidgets.QStackedWidget(self.frame_2)
        self.page_window.setObjectName("page_window")
        self.Page1 = QtWidgets.QWidget()
        self.Page1.setObjectName("Page1")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.Page1)
        self.horizontalLayout_32.setSpacing(12)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.scrollArea = QtWidgets.QScrollArea(self.Page1)
        self.scrollArea.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 909, 781))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget_23 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_23.setGeometry(QtCore.QRect(30, 650, 841, 71))
        self.widget_23.setMinimumSize(QtCore.QSize(361, 0))
        self.widget_23.setMaximumSize(QtCore.QSize(176666, 17666))
        self.widget_23.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:28px")
        self.widget_23.setObjectName("widget_23")
        self.frame_8 = QtWidgets.QFrame(self.widget_23)
        self.frame_8.setGeometry(QtCore.QRect(610, 10, 221, 51))
        self.frame_8.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 10, 100, 32))
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 32))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    margin-right:3px;\n"
" \n"
"    color: rgba(0, 0, 0, 166);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:1px outset rgb(212, 215, 220);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 10, 100, 32))
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 32))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    margin-right:3px;\n"
" \n"
"    color: rgba(0, 0, 0, 166);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:1px outset rgb(212, 215, 220);\n"
"    border-radius:12px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_12 = QtWidgets.QFrame(self.widget_23)
        self.frame_12.setGeometry(QtCore.QRect(10, 10, 551, 51))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 10, 461, 32))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.lineEdit_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("color: rgba(0, 0, 0, 35);\n"
"border:none;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_12)
        self.pushButton.setGeometry(QtCore.QRect(500, 10, 41, 41))
        self.pushButton.setStyleSheet("background-color: qlineargradient(x0:0, y0:1, x1:1, y1:1,stop:0.4  rgb(107, 128, 210));\n"
"image: url(:/buttom_white/img/buttom_white/发送_send.svg);\n"
"border-radius:16px;\n"
"padding:8px;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.widget_24 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_24.setGeometry(QtCore.QRect(480, 30, 400, 400))
        self.widget_24.setMinimumSize(QtCore.QSize(361, 0))
        self.widget_24.setMaximumSize(QtCore.QSize(176666, 17666))
        self.widget_24.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:28px")
        self.widget_24.setObjectName("widget_24")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.widget_24)
        self.graphicsView_2.setGeometry(QtCore.QRect(10, 10, 381, 381))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.widget_25 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_25.setGeometry(QtCore.QRect(20, 30, 400, 400))
        self.widget_25.setMinimumSize(QtCore.QSize(361, 0))
        self.widget_25.setMaximumSize(QtCore.QSize(176666, 17666))
        self.widget_25.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:28px")
        self.widget_25.setObjectName("widget_25")
        self.graphicsView = QtWidgets.QGraphicsView(self.widget_25)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 381, 381))
        self.graphicsView.setObjectName("graphicsView")
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_3.setGeometry(QtCore.QRect(550, 610, 24, 24))
        self.widget_3.setMinimumSize(QtCore.QSize(24, 24))
        self.widget_3.setMaximumSize(QtCore.QSize(24, 24))
        self.widget_3.setSizeIncrement(QtCore.QSize(32, 0))
        self.widget_3.setStyleSheet("image: url(:/buttom/img/buttom/放大_zoom-in.svg);")
        self.widget_3.setObjectName("widget_3")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(170, 430, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(620, 430, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(17)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_32.addWidget(self.scrollArea)
        self.page_window.addWidget(self.Page1)
        self.Page2 = QtWidgets.QWidget()
        self.Page2.setObjectName("Page2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Page2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.Page2)
        self.scrollArea_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 893, 765))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.widget_40 = QtWidgets.QWidget(self.scrollAreaWidgetContents_4)
        self.widget_40.setGeometry(QtCore.QRect(30, 530, 841, 71))
        self.widget_40.setMinimumSize(QtCore.QSize(361, 0))
        self.widget_40.setMaximumSize(QtCore.QSize(176666, 17666))
        self.widget_40.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:28px")
        self.widget_40.setObjectName("widget_40")
        self.frame_17 = QtWidgets.QFrame(self.widget_40)
        self.frame_17.setGeometry(QtCore.QRect(610, 10, 221, 51))
        self.frame_17.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_11.setGeometry(QtCore.QRect(0, 10, 100, 32))
        self.pushButton_11.setMinimumSize(QtCore.QSize(100, 32))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    margin-right:3px;\n"
" \n"
"    color: rgba(0, 0, 0, 166);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:1px outset rgb(212, 215, 220);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"}\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_12.setGeometry(QtCore.QRect(120, 10, 100, 32))
        self.pushButton_12.setMinimumSize(QtCore.QSize(100, 32))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    margin-right:3px;\n"
" \n"
"    color: rgba(0, 0, 0, 166);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:1px outset rgb(212, 215, 220);\n"
"    border-radius:12px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"}\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.frame_18 = QtWidgets.QFrame(self.widget_40)
        self.frame_18.setGeometry(QtCore.QRect(10, 10, 551, 51))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_18)
        self.lineEdit_7.setGeometry(QtCore.QRect(22, 9, 461, 32))
        self.lineEdit_7.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEdit_7.setStyleSheet("color: rgba(0, 0, 0, 35);\n"
"border:none;")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.widget_41 = QtWidgets.QWidget(self.frame_18)
        self.widget_41.setGeometry(QtCore.QRect(510, 10, 32, 32))
        self.widget_41.setMinimumSize(QtCore.QSize(32, 32))
        self.widget_41.setMaximumSize(QtCore.QSize(32, 32))
        self.widget_41.setSizeIncrement(QtCore.QSize(0, 2))
        self.widget_41.setStyleSheet("background-color: qlineargradient(x0:0, y0:1, x1:1, y1:1,stop:0.4  rgb(107, 128, 210));\n"
"image: url(:/buttom_white/img/buttom_white/发送_send.svg);\n"
"border-radius:16px;\n"
"padding:8px;")
        self.widget_41.setObjectName("widget_41")
        self.widget_42 = QtWidgets.QWidget(self.scrollAreaWidgetContents_4)
        self.widget_42.setGeometry(QtCore.QRect(480, 30, 400, 400))
        self.widget_42.setMinimumSize(QtCore.QSize(361, 0))
        self.widget_42.setMaximumSize(QtCore.QSize(176666, 17666))
        self.widget_42.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:28px")
        self.widget_42.setObjectName("widget_42")
        self.widget_43 = QtWidgets.QWidget(self.scrollAreaWidgetContents_4)
        self.widget_43.setGeometry(QtCore.QRect(20, 30, 400, 400))
        self.widget_43.setMinimumSize(QtCore.QSize(361, 0))
        self.widget_43.setMaximumSize(QtCore.QSize(176666, 17666))
        self.widget_43.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:28px")
        self.widget_43.setObjectName("widget_43")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_5.addWidget(self.scrollArea_2)
        self.page_window.addWidget(self.Page2)
        self.Page3 = QtWidgets.QWidget()
        self.Page3.setObjectName("Page3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Page3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.Page3)
        self.scrollArea_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.scrollArea_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 893, 765))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.widget_44 = QtWidgets.QWidget(self.scrollAreaWidgetContents_5)
        self.widget_44.setGeometry(QtCore.QRect(30, 570, 841, 71))
        self.widget_44.setMinimumSize(QtCore.QSize(361, 0))
        self.widget_44.setMaximumSize(QtCore.QSize(176666, 17666))
        self.widget_44.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:28px")
        self.widget_44.setObjectName("widget_44")
        self.frame_19 = QtWidgets.QFrame(self.widget_44)
        self.frame_19.setGeometry(QtCore.QRect(610, 10, 221, 51))
        self.frame_19.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_19)
        self.pushButton_13.setGeometry(QtCore.QRect(0, 10, 100, 32))
        self.pushButton_13.setMinimumSize(QtCore.QSize(100, 32))
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"    margin-right:3px;\n"
" \n"
"    color: rgba(0, 0, 0, 166);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:1px outset rgb(212, 215, 220);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"}\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_19)
        self.pushButton_14.setGeometry(QtCore.QRect(120, 10, 100, 32))
        self.pushButton_14.setMinimumSize(QtCore.QSize(100, 32))
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"    margin-right:3px;\n"
" \n"
"    color: rgba(0, 0, 0, 166);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:1px outset rgb(212, 215, 220);\n"
"    border-radius:12px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"}\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.frame_20 = QtWidgets.QFrame(self.widget_44)
        self.frame_20.setGeometry(QtCore.QRect(10, 10, 551, 51))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_20)
        self.lineEdit_8.setGeometry(QtCore.QRect(22, 9, 461, 32))
        self.lineEdit_8.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEdit_8.setStyleSheet("color: rgba(0, 0, 0, 35);\n"
"border:none;")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.widget_45 = QtWidgets.QWidget(self.frame_20)
        self.widget_45.setGeometry(QtCore.QRect(510, 10, 32, 32))
        self.widget_45.setMinimumSize(QtCore.QSize(32, 32))
        self.widget_45.setMaximumSize(QtCore.QSize(32, 32))
        self.widget_45.setSizeIncrement(QtCore.QSize(0, 2))
        self.widget_45.setStyleSheet("background-color: qlineargradient(x0:0, y0:1, x1:1, y1:1,stop:0.4  rgb(107, 128, 210));\n"
"image: url(:/buttom_white/img/buttom_white/发送_send.svg);\n"
"border-radius:16px;\n"
"padding:8px;")
        self.widget_45.setObjectName("widget_45")
        self.widget_46 = QtWidgets.QWidget(self.scrollAreaWidgetContents_5)
        self.widget_46.setGeometry(QtCore.QRect(480, 30, 400, 400))
        self.widget_46.setMinimumSize(QtCore.QSize(361, 0))
        self.widget_46.setMaximumSize(QtCore.QSize(176666, 17666))
        self.widget_46.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:28px")
        self.widget_46.setObjectName("widget_46")
        self.widget_47 = QtWidgets.QWidget(self.scrollAreaWidgetContents_5)
        self.widget_47.setGeometry(QtCore.QRect(20, 30, 400, 400))
        self.widget_47.setMinimumSize(QtCore.QSize(361, 0))
        self.widget_47.setMaximumSize(QtCore.QSize(176666, 17666))
        self.widget_47.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:28px")
        self.widget_47.setObjectName("widget_47")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_5)
        self.horizontalLayout_6.addWidget(self.scrollArea_3)
        self.page_window.addWidget(self.Page3)
        self.Page4 = QtWidgets.QWidget()
        self.Page4.setObjectName("Page4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.Page4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.Page4)
        self.scrollArea_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.scrollArea_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_4.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 893, 765))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.widget_48 = QtWidgets.QWidget(self.scrollAreaWidgetContents_6)
        self.widget_48.setGeometry(QtCore.QRect(20, 650, 841, 71))
        self.widget_48.setMinimumSize(QtCore.QSize(361, 0))
        self.widget_48.setMaximumSize(QtCore.QSize(176666, 17666))
        self.widget_48.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:28px")
        self.widget_48.setObjectName("widget_48")
        self.frame_21 = QtWidgets.QFrame(self.widget_48)
        self.frame_21.setGeometry(QtCore.QRect(610, 10, 221, 51))
        self.frame_21.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_21)
        self.pushButton_15.setGeometry(QtCore.QRect(0, 10, 100, 32))
        self.pushButton_15.setMinimumSize(QtCore.QSize(100, 32))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"    margin-right:3px;\n"
" \n"
"    color: rgba(0, 0, 0, 166);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:1px outset rgb(212, 215, 220);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"}\n"
"")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_21)
        self.pushButton_16.setGeometry(QtCore.QRect(120, 10, 100, 32))
        self.pushButton_16.setMinimumSize(QtCore.QSize(100, 32))
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"    margin-right:3px;\n"
" \n"
"    color: rgba(0, 0, 0, 166);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:1px outset rgb(212, 215, 220);\n"
"    border-radius:12px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"}\n"
"")
        self.pushButton_16.setObjectName("pushButton_16")
        self.frame_22 = QtWidgets.QFrame(self.widget_48)
        self.frame_22.setGeometry(QtCore.QRect(10, 10, 551, 51))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_22)
        self.lineEdit_9.setGeometry(QtCore.QRect(22, 9, 461, 32))
        self.lineEdit_9.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEdit_9.setStyleSheet("color: rgba(0, 0, 0, 35);\n"
"border:none;")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.widget_49 = QtWidgets.QWidget(self.frame_22)
        self.widget_49.setGeometry(QtCore.QRect(510, 10, 32, 32))
        self.widget_49.setMinimumSize(QtCore.QSize(32, 32))
        self.widget_49.setMaximumSize(QtCore.QSize(32, 32))
        self.widget_49.setSizeIncrement(QtCore.QSize(0, 2))
        self.widget_49.setStyleSheet("background-color: qlineargradient(x0:0, y0:1, x1:1, y1:1,stop:0.4  rgb(107, 128, 210));\n"
"image: url(:/buttom_white/img/buttom_white/发送_send.svg);\n"
"border-radius:16px;\n"
"padding:8px;")
        self.widget_49.setObjectName("widget_49")
        self.widget_50 = QtWidgets.QWidget(self.scrollAreaWidgetContents_6)
        self.widget_50.setGeometry(QtCore.QRect(480, 30, 400, 400))
        self.widget_50.setMinimumSize(QtCore.QSize(361, 0))
        self.widget_50.setMaximumSize(QtCore.QSize(176666, 17666))
        self.widget_50.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:28px")
        self.widget_50.setObjectName("widget_50")
        self.widget_51 = QtWidgets.QWidget(self.scrollAreaWidgetContents_6)
        self.widget_51.setGeometry(QtCore.QRect(20, 30, 400, 400))
        self.widget_51.setMinimumSize(QtCore.QSize(361, 0))
        self.widget_51.setMaximumSize(QtCore.QSize(176666, 17666))
        self.widget_51.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:28px")
        self.widget_51.setObjectName("widget_51")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_6)
        self.horizontalLayout_7.addWidget(self.scrollArea_4)
        self.page_window.addWidget(self.Page4)
        self.verticalLayout_30.addWidget(self.page_window)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.page_window.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Liu Guang"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "嵌入字符串"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "嵌入图片"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "嵌入比特流"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "设置"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_54.setText(_translate("MainWindow", "StatusLSale"))
        self.label.setText(_translate("MainWindow", "数字水印"))
        self.pushButton_3.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_2.setText(_translate("MainWindow", "水印解析"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "输入嵌入的字符串"))
        self.label_2.setText(_translate("MainWindow", "原图像"))
        self.label_3.setText(_translate("MainWindow", "已添加水印"))
        self.pushButton_11.setText(_translate("MainWindow", "button1"))
        self.pushButton_12.setText(_translate("MainWindow", "make offer"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "输入嵌入的字符串"))
        self.pushButton_13.setText(_translate("MainWindow", "button1"))
        self.pushButton_14.setText(_translate("MainWindow", "make offer"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "输入嵌入的字符串"))
        self.pushButton_15.setText(_translate("MainWindow", "button1"))
        self.pushButton_16.setText(_translate("MainWindow", "make offer"))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "输入嵌入的字符串"))
import resources_rc
